// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Xamarin.NohanaImagePicker
{
	public partial class AnimatableNavigationController : UINavigationController
	{
		public AnimatableNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
