// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Xamarin.NohanaImagePicker
{
	public partial class AssetDetailListViewController : UICollectionViewController
	{
		public AssetDetailListViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
