// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Xamarin.NohanaImagePicker
{
	public partial class AssetDetailCell : UICollectionViewCell
	{
		public AssetDetailCell (IntPtr handle) : base (handle)
		{
		}
	}
}
